services:
  app:
    build: .
    container_name: resemblyzer_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data: